/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BundleDiff = {
  created?: Array<string> | undefined;
  deleted?: Array<string> | undefined;
  modified?: Array<string> | undefined;
};

/** @internal */
export const BundleDiff$inboundSchema: z.ZodType<
  BundleDiff,
  z.ZodTypeDef,
  unknown
> = z.object({
  created: z.array(z.string()).optional(),
  deleted: z.array(z.string()).optional(),
  modified: z.array(z.string()).optional(),
});

/** @internal */
export type BundleDiff$Outbound = {
  created?: Array<string> | undefined;
  deleted?: Array<string> | undefined;
  modified?: Array<string> | undefined;
};

/** @internal */
export const BundleDiff$outboundSchema: z.ZodType<
  BundleDiff$Outbound,
  z.ZodTypeDef,
  BundleDiff
> = z.object({
  created: z.array(z.string()).optional(),
  deleted: z.array(z.string()).optional(),
  modified: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BundleDiff$ {
  /** @deprecated use `BundleDiff$inboundSchema` instead. */
  export const inboundSchema = BundleDiff$inboundSchema;
  /** @deprecated use `BundleDiff$outboundSchema` instead. */
  export const outboundSchema = BundleDiff$outboundSchema;
  /** @deprecated use `BundleDiff$Outbound` instead. */
  export type Outbound = BundleDiff$Outbound;
}

export function bundleDiffToJSON(bundleDiff: BundleDiff): string {
  return JSON.stringify(BundleDiff$outboundSchema.parse(bundleDiff));
}

export function bundleDiffFromJSON(
  jsonString: string,
): SafeParseResult<BundleDiff, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BundleDiff$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BundleDiff' from JSON`,
  );
}
