/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class CreateContextRestrictionRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "project_id" })
    projectId?: string;
}

export class CreateContextRestrictionRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody: CreateContextRestrictionRequestBody;

    /**
     * An opaque identifier of a context.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=context_id" })
    contextId: string;
}

/**
 * Request conflict.
 */
export class CreateContextRestrictionContextResponse409ResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Credentials provided are invalid.
 */
export class CreateContextRestrictionContextResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Bad request.
 */
export class CreateContextRestrictionResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

export class CreateContextRestrictionResponse extends SpeakeasyBase {
    /**
     * Bad request.
     */
    @SpeakeasyMetadata()
    fourHundredApplicationJsonObject?: CreateContextRestrictionResponseBody;

    /**
     * Request conflict.
     */
    @SpeakeasyMetadata()
    fourHundredAndNineApplicationJsonObject?: CreateContextRestrictionContextResponse409ResponseBody;

    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Credentials provided are invalid.
     */
    @SpeakeasyMetadata()
    object?: CreateContextRestrictionContextResponseBody;

    /**
     * Successful response.
     */
    @SpeakeasyMetadata()
    restrictionCreated?: shared.RestrictionCreated;
}
