/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class CreatePolicyBundleRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    bundlePayload?: shared.BundlePayload;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=context" })
    context: string;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=dry" })
    dry?: boolean;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=ownerID" })
    ownerID: string;
}

/**
 * Something unexpected happened on the server.
 */
export class CreatePolicyBundle500ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    error: string;
}

/**
 * The request exceeds the maximum payload size for policy bundles ~2.5Mib
 *
 * @remarks
 *
 */
export class CreatePolicyBundle413ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    error: string;
}

/**
 * The user is forbidden from making this request
 *
 * @remarks
 *
 */
export class CreatePolicyBundle403ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    error: string;
}

/**
 * The request is unauthorized
 *
 * @remarks
 *
 */
export class CreatePolicyBundle401ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    error: string;
}

/**
 * The request is malformed (e.g, a given path parameter is invalid)
 *
 * @remarks
 *
 */
export class CreatePolicyBundle400ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    error: string;
}

export class CreatePolicyBundleResponse extends SpeakeasyBase {
    /**
     * Policy-Bundle diff successfully returned.
     */
    @SpeakeasyMetadata()
    bundleDiff?: shared.BundleDiff;

    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * The request is malformed (e.g, a given path parameter is invalid)
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    createPolicyBundle400ApplicationJSONObject?: CreatePolicyBundle400ApplicationJSON;

    /**
     * The request is unauthorized
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    createPolicyBundle401ApplicationJSONObject?: CreatePolicyBundle401ApplicationJSON;

    /**
     * The user is forbidden from making this request
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    createPolicyBundle403ApplicationJSONObject?: CreatePolicyBundle403ApplicationJSON;

    /**
     * The request exceeds the maximum payload size for policy bundles ~2.5Mib
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    createPolicyBundle413ApplicationJSONObject?: CreatePolicyBundle413ApplicationJSON;

    /**
     * Something unexpected happened on the server.
     */
    @SpeakeasyMetadata()
    createPolicyBundle500ApplicationJSONObject?: CreatePolicyBundle500ApplicationJSON;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
