/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class GetAllInsightsBranchesRequest extends SpeakeasyBase {
    /**
     * Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped. For projects that use GitLab or GitHub App, use `circleci` as the `vcs-slug`, replace `org-name` with the organization ID (found in Organization Settings), and replace `repo-name` with the project ID (found in Project Settings).
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=project-slug" })
    projectSlug: string;

    /**
     * The name of a workflow. If not passed we will scope the API call to the project.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=workflow-name" })
    workflowName?: string;
}

/**
 * Error response.
 */
export class GetAllInsightsBranchesInsightsResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Project branches response.
 */
export class GetAllInsightsBranchesResponseBody extends SpeakeasyBase {
    /**
     * A list of all the branches for a given project.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "branches" })
    branches: string[];

    /**
     * The unique ID of the organization
     */
    @SpeakeasyMetadata()
    @Expose({ name: "org_id" })
    orgId: any;

    /**
     * The unique ID of the project
     */
    @SpeakeasyMetadata()
    @Expose({ name: "project_id" })
    projectId: any;
}

export class GetAllInsightsBranchesResponse extends SpeakeasyBase {
    /**
     * A list of branches for a project
     */
    @SpeakeasyMetadata()
    twoHundredApplicationJsonObject?: GetAllInsightsBranchesResponseBody;

    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Error response.
     */
    @SpeakeasyMetadata()
    defaultApplicationJsonObject?: GetAllInsightsBranchesInsightsResponseBody;
}
