/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetPipelineValuesByIdRequest = {
  /**
   * The unique ID of the pipeline.
   */
  pipelineId: string;
};

/**
 * Error response.
 */
export type GetPipelineValuesByIdResponseBody = {
  message?: string | undefined;
};

export type ResponseBody = string | number | boolean;

export type GetPipelineValuesByIdResponse =
  | GetPipelineValuesByIdResponseBody
  | { [k: string]: string | number | boolean };

/** @internal */
export const GetPipelineValuesByIdRequest$inboundSchema: z.ZodType<
  GetPipelineValuesByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "pipeline-id": z.string(),
}).transform((v) => {
  return remap$(v, {
    "pipeline-id": "pipelineId",
  });
});

/** @internal */
export type GetPipelineValuesByIdRequest$Outbound = {
  "pipeline-id": string;
};

/** @internal */
export const GetPipelineValuesByIdRequest$outboundSchema: z.ZodType<
  GetPipelineValuesByIdRequest$Outbound,
  z.ZodTypeDef,
  GetPipelineValuesByIdRequest
> = z.object({
  pipelineId: z.string(),
}).transform((v) => {
  return remap$(v, {
    pipelineId: "pipeline-id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPipelineValuesByIdRequest$ {
  /** @deprecated use `GetPipelineValuesByIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetPipelineValuesByIdRequest$inboundSchema;
  /** @deprecated use `GetPipelineValuesByIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetPipelineValuesByIdRequest$outboundSchema;
  /** @deprecated use `GetPipelineValuesByIdRequest$Outbound` instead. */
  export type Outbound = GetPipelineValuesByIdRequest$Outbound;
}

export function getPipelineValuesByIdRequestToJSON(
  getPipelineValuesByIdRequest: GetPipelineValuesByIdRequest,
): string {
  return JSON.stringify(
    GetPipelineValuesByIdRequest$outboundSchema.parse(
      getPipelineValuesByIdRequest,
    ),
  );
}

export function getPipelineValuesByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetPipelineValuesByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPipelineValuesByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPipelineValuesByIdRequest' from JSON`,
  );
}

/** @internal */
export const GetPipelineValuesByIdResponseBody$inboundSchema: z.ZodType<
  GetPipelineValuesByIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
});

/** @internal */
export type GetPipelineValuesByIdResponseBody$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const GetPipelineValuesByIdResponseBody$outboundSchema: z.ZodType<
  GetPipelineValuesByIdResponseBody$Outbound,
  z.ZodTypeDef,
  GetPipelineValuesByIdResponseBody
> = z.object({
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPipelineValuesByIdResponseBody$ {
  /** @deprecated use `GetPipelineValuesByIdResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetPipelineValuesByIdResponseBody$inboundSchema;
  /** @deprecated use `GetPipelineValuesByIdResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    GetPipelineValuesByIdResponseBody$outboundSchema;
  /** @deprecated use `GetPipelineValuesByIdResponseBody$Outbound` instead. */
  export type Outbound = GetPipelineValuesByIdResponseBody$Outbound;
}

export function getPipelineValuesByIdResponseBodyToJSON(
  getPipelineValuesByIdResponseBody: GetPipelineValuesByIdResponseBody,
): string {
  return JSON.stringify(
    GetPipelineValuesByIdResponseBody$outboundSchema.parse(
      getPipelineValuesByIdResponseBody,
    ),
  );
}

export function getPipelineValuesByIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetPipelineValuesByIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPipelineValuesByIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPipelineValuesByIdResponseBody' from JSON`,
  );
}

/** @internal */
export const ResponseBody$inboundSchema: z.ZodType<
  ResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.number().int(), z.boolean()]);

/** @internal */
export type ResponseBody$Outbound = string | number | boolean;

/** @internal */
export const ResponseBody$outboundSchema: z.ZodType<
  ResponseBody$Outbound,
  z.ZodTypeDef,
  ResponseBody
> = z.union([z.string(), z.number().int(), z.boolean()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseBody$ {
  /** @deprecated use `ResponseBody$inboundSchema` instead. */
  export const inboundSchema = ResponseBody$inboundSchema;
  /** @deprecated use `ResponseBody$outboundSchema` instead. */
  export const outboundSchema = ResponseBody$outboundSchema;
  /** @deprecated use `ResponseBody$Outbound` instead. */
  export type Outbound = ResponseBody$Outbound;
}

export function responseBodyToJSON(responseBody: ResponseBody): string {
  return JSON.stringify(ResponseBody$outboundSchema.parse(responseBody));
}

export function responseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseBody' from JSON`,
  );
}

/** @internal */
export const GetPipelineValuesByIdResponse$inboundSchema: z.ZodType<
  GetPipelineValuesByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetPipelineValuesByIdResponseBody$inboundSchema),
  z.record(z.union([z.string(), z.number().int(), z.boolean()])),
]);

/** @internal */
export type GetPipelineValuesByIdResponse$Outbound =
  | GetPipelineValuesByIdResponseBody$Outbound
  | { [k: string]: string | number | boolean };

/** @internal */
export const GetPipelineValuesByIdResponse$outboundSchema: z.ZodType<
  GetPipelineValuesByIdResponse$Outbound,
  z.ZodTypeDef,
  GetPipelineValuesByIdResponse
> = z.union([
  z.lazy(() => GetPipelineValuesByIdResponseBody$outboundSchema),
  z.record(z.union([z.string(), z.number().int(), z.boolean()])),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPipelineValuesByIdResponse$ {
  /** @deprecated use `GetPipelineValuesByIdResponse$inboundSchema` instead. */
  export const inboundSchema = GetPipelineValuesByIdResponse$inboundSchema;
  /** @deprecated use `GetPipelineValuesByIdResponse$outboundSchema` instead. */
  export const outboundSchema = GetPipelineValuesByIdResponse$outboundSchema;
  /** @deprecated use `GetPipelineValuesByIdResponse$Outbound` instead. */
  export type Outbound = GetPipelineValuesByIdResponse$Outbound;
}

export function getPipelineValuesByIdResponseToJSON(
  getPipelineValuesByIdResponse: GetPipelineValuesByIdResponse,
): string {
  return JSON.stringify(
    GetPipelineValuesByIdResponse$outboundSchema.parse(
      getPipelineValuesByIdResponse,
    ),
  );
}

export function getPipelineValuesByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPipelineValuesByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPipelineValuesByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPipelineValuesByIdResponse' from JSON`,
  );
}
