/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class ListEnvVarsRequest extends SpeakeasyBase {
  /**
   * Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=project-slug",
  })
  projectSlug: string;
}

/**
 * Error response.
 */
export class ListEnvVarsDefaultApplicationJSON extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;
}

export class ListEnvVarsEnvironmentVariableListResponseEnvironmentVariablePair extends SpeakeasyBase {
  /**
   * The name of the environment variable.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * The value of the environment variable.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "value" })
  value: string;
}

/**
 * A sequence of environment variables.
 */
export class ListEnvVarsEnvironmentVariableListResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({
    elemType: ListEnvVarsEnvironmentVariableListResponseEnvironmentVariablePair,
  })
  @Expose({ name: "items" })
  @Type(() => ListEnvVarsEnvironmentVariableListResponseEnvironmentVariablePair)
  items: ListEnvVarsEnvironmentVariableListResponseEnvironmentVariablePair[];

  /**
   * A token to pass as a `page-token` query parameter to return the next page of results.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "next_page_token" })
  nextPageToken: string;
}

export class ListEnvVarsResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * A sequence of environment variables.
   */
  @SpeakeasyMetadata()
  environmentVariableListResponse?: ListEnvVarsEnvironmentVariableListResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Error response.
   */
  @SpeakeasyMetadata()
  listEnvVarsDefaultApplicationJSONObject?: ListEnvVarsDefaultApplicationJSON;
}
