name: Generate

on:
  workflow_dispatch: {} # Allows manual triggering of the workflow to generate SDK
  schedule:
    - cron: 0 0 * * * # Runs every day at midnight

jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v7
    with:
      speakeasy_version: latest
      openapi_doc_location: blob:https://circleci.com/99952f18-d475-4831-96e4-146d36c4ff79
      languages: |-
        - typescript
      publish_typescript: true
      publish_python: true
      mode: pr
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}